---

- hosts: all
  vars:
    packages:
      - git
      - curl
      - unzip
      - php7.2-cli
      - php7.2-gd
      - php7.2-curl
      - php7.2-dom
    php_ini:
      "default_charset": "UTF-8"
      "date.timezone":   "UTC"
    phars:
        composer: https://getcomposer.org/composer.phar
  tasks:
    - apt_repository: repo="ppa:ondrej/php" update_cache=yes state=present
      environment: {LC_ALL: C.UTF-8}
    - apt: name={{ packages }} update_cache=yes state=latest
    - lineinfile: dest=/etc/php/7.2/cli/php.ini regexp="^{{ item.key }}" line="{{ item.key }}={{ item.value }}" state=present
      with_dict: "{{ php_ini }}"
    - get_url: url={{ item.value }} dest=/usr/local/bin/{{ item.key }} mode=0755
      with_dict: "{{ phars }}"
